name: Create build artifact

inputs:
  app-env:
    required: true

  linode-pat:
    required: true

  linode-label:
    required: true

  linode-root-pass:
    required: false

  linode-admin-users-file:
    required: false

  domains:
    required: true

  email:
    required: true

  deploy-artifact:
    required: true

  deploy-command:
    required: true

  deploy-directory:
    required: false

  deploy-user:
    required: false
    default: deploy

  deploy-user-private-key:
    required: true

  deploy-user-public-key:
    required: true

  healthcheck-urls:
    required: false

runs:
  using: node12
  main: dist/index.js
