on: push

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install, build, package
        run: |
          npm install
          npm run build
          npm run package
          rm -rf node_modules index.js

      - name: Commit newly built/packaged action
        uses: EndBug/add-and-commit@v5
        with:
          author_name: github-actions
          message: 'ci: automated build'
          add: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
